apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/limit-connections: "400"
    nginx.ingress.kubernetes.io/limit-rps: "400"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-XSS-Protection "1; mode=block";
      add_header Strict-Transport-Security "max-age=31536000";
      add_header Cache-Control no-store;
      add_header Pragma no-cache;
      add_header X-Frame-Options "SAMEORIGIN";
      add_header Content-Security-Policy "script-src 'self' 'unsafe-eval' 'unsafe-inline' *.baidu.com busuanzi.ibruce.info api.ip.sb cdn.jsdelivr.net;object-src 'none';frame-ancestors 'self'";
  name: openlookeng-website-ingress-main
spec:
  tls:
    - hosts:
        - backup.openlookeng.io
      secretName: openlookeng-website-tls-main
  rules:
    - host: backup.openlookeng.io
      http:
        paths:
          - backend:
              serviceName: openlookeng-bot-internal
              servicePort: 80
            path: /cla
          - backend:
              serviceName: openlookeng-website-internal
              servicePort: 80
            path: /
