apiVersion: v1
data:
  config.yaml: |
    giteeToken: "stored in secrets and will be injected via environment"
    webhookSecret: "stored in secrets and will be injected via environment"
    databaseType: "mysql"
    databaseHost: "172.16.1.74"
    databasePort: 3306
    databaseName: "cibot-debug"
    databaseUserName: "stored in secrets and will be injected via environment"
    databasePassword: "stored in secrets and will be injected via environment"
    #the flag that pull request commit_id has changed
    prUpdateLabelFlag: "source_branch_changed"
    #List of labels that need to be deleted after the commit_id is changed
    delLabels:
      - lgtm
      - approved
      - ci_successful
    checkPrReviewer: true
    # Tips for setting reviewers
    setReviewerTip: "Please assign one reviewer at least, visit https://gitee.com/mindspore/community/tree/master/sigs to check all sigs and maintainers in community."
    # Config option for lgtm required counts
    lgtmCountsRequired: 1
    extraLgtmCountRequired:
      - lcrType: repo
        lcrName: ci-bot/k9s
        lcrCount: 2
    requiringLabels:
      - ci-bot-cla/yes
    commitsThreshold: 1
    squashCommitLabel: stat/need-squash
    watchProjectFiles:
      - watchProjectFileOwner: ci-bot
        watchprojectFileRepo: community
        watchprojectFilePath: repository/georgecaotest.yaml
        watchProjectFileRef: master
    watchProjectFileDuration: 40
    watchSigFiles:
      - watchSigFileOwner: ci-bot
        watchSigFileRepo: community
        watchSigFilePath: sig/sigs.yaml
        watchSigFileRef: master
    watchSigFileDuration: 60
    watchOwnerFiles:
      - watchOwnerFileOwner: ci-bot
        watchOwnerFileRepo: community
        watchOwnerFilePath: sig/*/OWNERS
        watchOwnerFileRef: master
    watchOwnerFileDuration: 80
    watchFrozenFile:
      - frozenFileOwner: ci-bot
        frozenFileRepo: release-management
        frozenFilePath: release-management.yaml
        frozenFileRef: master
    watchFrozenDuration: 50
    botName: openeuler-ci-bot-debug
    communityName: ci-bot
    claLink: https://openeuler.org/en/cla.html
    commandLink: https://gitee.com/openeuler/community/blob/master/en/sig-infrastructure/command.md
    contactEmail: contact@openeuler.org
    accordingfile: src-openeuler.yaml
    newfileowner: src-openeuler
    newfilerepo: obs_meta
    newfilebranch: master
    tmpservicefile: _service
    tmpservicepath: master/openEuler:Factory/#projectname#/_service
    guideurl: https://gitee.com/georgecaotest/community/tree/master/zh/contributors
    autoDetectCla: false
  gitee_oauth2_client_code: "stored in secrets and will be injected via environment"
  gitee_oauth2_secret: "stored in secrets and will be injected via environment"
kind: ConfigMap
metadata:
  name: bot-configmap
  namespace: bot

