resources:
- https://github.com/opensourceways/app-bot/deploy?ref=master
commonLabels:
  app: openeuler-bot-debug
nameSuffix: -debug
namespace: bot-debug
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- configmap.yaml
- deployment.yaml
- secrets.yaml
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/ci-bot
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/ci-bot
  newTag: d6b51dab5fa2c844b30c96641884a8626239e4a6.1604630719
