---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openlookeng-website-frontend
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: websiteinfo
  template:
    metadata:
      labels:
        app: websiteinfo
    spec:
      containers:
      - name: websitepod
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openlookeng_website:9621f3d66a68d6243720b00790dbdd79e775aec0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
