resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- purge-cache.yaml
- purge-secrets.yaml
commonLabels:
  app: openlookeng-website-frontend
namespace: openlookeng-website-frontend
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openlookeng_website
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openlookeng_website
  newTag: 733db0cf487a0a48ff2e4f77949fdc5e2e5316fb
