# Config web service
---
apiVersion: v1
kind: Service
metadata:
  name: openlookeng-website-frontend-service
spec:
  ports:
    - name: httpport
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: openlookeng-website-frontend
  type: ClusterIP
