resources:
- ingress.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- namespace.yaml
- secret.yaml
namespace: opendesign-datapertus
commonAnnotations:
  kubernetes.ops.cluster: openeuler-hk-cluster
  kubernetes.ops.community: openeuler
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: debian
  kubernetes.ops.owner: yuchunao
  kubernetes.ops.region: hk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/datastat/openeuler
  newTag: ca01afad330acc177f83c89661b9d973bdbd8aee
