#  www-ingress   ingress-backend  ingress-main minisote-ingress
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/limit-connections: "2000"
    nginx.ingress.kubernetes.io/limit-rps: "2000"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-XSS-Protection "1; mode=block";
      add_header Strict-Transport-Security "max-age=31536000";
      add_header X-Frame-Options "ALLOW-FROM https://vhall.huawei.com";
      add_header X-Cache-Status $upstream_cache_status;
      add_header Content-Security-Policy "worker-src 'self' 'unsafe-eval' 'unsafe-inline' * blob:";
      set $Real $proxy_add_x_forwarded_for;
      if ( $Real ~ (\d+)\.(\d+)\.(\d+)\.(\d+),(.*) ){
          set $Real $1.$2.$3.$4;
      }
      proxy_set_header True-Client-IP $Real;
    nginx.ingress.kubernetes.io/server-snippet: |
      rewrite ^/zh/other/cla https://clasign.osinfra.cn/sign/Z2l0ZWUlMkZvcGVuZXVsZXI= redirect;
      rewrite ^/en/other/cla https://clasign.osinfra.cn/sign/Z2l0ZWUlMkZvcGVuZXVsZXI= redirect;
      rewrite ^/zh/docs(/|$)(.*) https://docs.openeuler.org/zh/docs/$2 redirect;
      rewrite ^/en/docs(/|$)(.*) https://docs.openeuler.org/en/docs/$2 redirect;
      rewrite ^/ru(/|$)(.*) https://ru.openeuler.org/ru/$2 redirect;
      rewrite ^/zh/other/migration(/|$)(.*)                     /zh/migration/ redirect;
      rewrite ^/zh/interaction/summit-list/devday2022/          https://v1.openeuler.org/zh/interaction/summit-list/devday2022/ redirect;
      rewrite ^/zh/interaction/summit-list/summit2021/          https://v1.openeuler.org/zh/interaction/summit-list/summit2021/ redirect;
      rewrite ^/zh/interaction/summit-list/devday2021/          https://v1.openeuler.org/zh/interaction/summit-list/devday2021/ redirect;
      rewrite ^/zh/interaction/summit-list/$                    https://v1.openeuler.org/zh/interaction/summit-list/ redirect;
      rewrite ^/zh/interaction/summit-list/list/                https://v1.openeuler.org/zh/interaction/summit-list/list/ redirect;
      rewrite ^/zh/security/approve/                            https://www.openeuler.org/zh/approve/ redirect;
      rewrite ^/zh/security/compatibility/                      https://www.openeuler.org/zh/compatibility/ redirect;
      rewrite ^/zh/sig/sig-list/sig-detail.html?(.*)            https://www.openeuler.org/zh/sig/sig-detail/?$1 redirect;
      rewrite ^/en/sig/sig-list/sig-detail.html?(.*)            https://www.openeuler.org/en/sig/sig-detail/?$1 redirect;
      rewrite ^/zh/migration/guidance/(1-summary|2-attention|3-process|4-assessment|5-adaptive|6-stock-migration|7-increased-migration|8-updated|9-followup)  /zh/migration/guidance/ permanent;
      rewrite ^/zh/migration/implement-guide/                   /zh/migration/contact/ permanent;
      rewrite ^/zh/interaction/salon-list/$                     /zh/interaction/event-list/ permanent;
      rewrite ^/zh/interaction/salon-list/detail/(.*)           /zh/interaction/event-list/review/detail/$1 permanent;
      rewrite ^/zh/security/safety-bulletin/$                   /zh/security/security-bulletins/         permanent;
      rewrite ^/zh/security/safety-bulletin/detail/             /zh/security/security-bulletins/detail/  permanent;
  name: openeuler-v2-www-website-ingress
spec:
  tls:
    - hosts:
        - www.openeuler.org
      secretName: openeuler-org-tls
  rules:
    - host: www.openeuler.org
      http:
        paths:
          - backend:
              serviceName: website-frontend-service
              servicePort: 80
            path: /
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/custom-http-errors: "400,500"
  name: website-v2-www-ingress-backend
spec:
  tls:
    - hosts:
        - www.openeuler.org
      secretName: openeuler-org-tls
  rules:
    - host: www.openeuler.org
      http:
        paths:
          - backend:
              serviceName: website-backend-service
              servicePort: 80
            path: /api-node(/|$)(.*)
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-snippet: |
      rewrite ^/(.*)       https://www.openeuler.org/$1 redirect;
  name: website-v2-ingress-main
spec:
  tls:
    - hosts:
        - openeuler.org
      secretName: openeuler-org-tls
  rules:
    - host: openeuler.org
      http:
        paths:
          - backend:
              serviceName: website-frontend-service
              servicePort: 80
            path: /
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/temporal-redirect: https://www.openeuler.org/zh/other/projects/isula/
  name: isula-ingress
spec:
  tls:
    - hosts:
        - isula.openeuler.org
      secretName: openeuler-org-tls
  rules:
    - host: isula.openeuler.org
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/temporal-redirect: https://www.openeuler.org/zh/other/projects/atune/
  name: a-tune-ingress
spec:
  tls:
    - hosts:
        - a-tune.openeuler.org
      secretName: openeuler-org-tls
  rules:
    - host: a-tune.openeuler.org
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/temporal-redirect: https://www.openeuler.org/zh/other/projects/stratovirt/
  name: stratovirt-ingress
spec:
  tls:
    - hosts:
        - stratovirt.openeuler.org
      secretName: openeuler-org-tls
  rules:
    - host: stratovirt.openeuler.org
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/temporal-redirect: https://www.openeuler.org/zh/other/projects/bishengjdk/
  name: bisheng-ingress
spec:
  tls:
    - hosts:
        - bishengjdk.openeuler.org
      secretName: openeuler-org-tls
  rules:
    - host: bishengjdk.openeuler.org
