apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- secrets.yaml
- service.yaml
- namespace.yaml
- pvc.yaml
- cronjob.yaml
namespace: patchwork
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/patchwork/patchwork
  newTag: main-ecfc1d9
