kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- namespace.yaml
- deployment.yaml
- pvc.yaml
- service.yaml
- secrets.yaml
- configmap.yaml
commonLabels:
  label: mirrorbits
commonAnnotations:
  email: tommylikehu@gmail.com
  owner: tommylikehu
namespace: repo-mirrorbits
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/repo-mirrorbits
  newTag: b232da69ad40dc81b9827950fa1c2732b982eeff
