resources:
  - https://github.com/opensourceways/app-jenkins/deploy-without-agent?ref=stable
  - secrets.yaml
  - namespace.yaml
  - es-secrets.yaml
commonLabels:
  app: openeuler-jenkins
patchesStrategicMerge:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
namespace: jenkins
