resources:
- deployment.yaml
- service.yaml
- secrets.yaml
commonLabels:
  app: cve-manager-analysis
  owner: zhangjianjun
commonAnnotations:
  email: 841670711@qq.com
  owner: zhangjianjun
namespace: cve-manager
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/cve-manager-analysis
  newTag: ae277e5b9101015c0da41676c6a27240733df44d
