resources:
- deployment.yaml
- secrets.yaml
commonLabels:
  app: cve-manager-analysis
namespace: cve-manager
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/cve-manager-analysis
  newTag: 0cb628241fcc309dc846f018581bbe979614ba58
