apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-XSS-Protection "1; mode=block";
      add_header Strict-Transport-Security "max-age=31536000";
      add_header X-Frame-Options "DENY";
      add_header Content-Security-Policy "script-src 'self' *.baidu.com ers.baidu.com 'unsafe-eval' 'unsafe-inline';object-src 'none';frame-ancestors 'self'";
  name: pkgmange-web-ingress
spec:
  tls:
    - hosts:
        - pkgmanage.openeuler.org
      secretName: pkgmanage-tls
  rules:
    - host: pkgmanage.openeuler.org
      http:
        paths:
          - backend:
              serviceName: package-manage-web
              servicePort: 8080
            path: /
