resources:
- namespace.yaml
- ingress.yaml
- service.yaml
- server.yaml
- website.yaml
- secret.yaml
namespace: openeuler-sbom-service
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-sbom-server
  newTag: v1.0.20230731201640
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-sbom-service
  newTag: v1.0.20221219092612
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-sbom-website
  newTag: v1.0.20230801161406
