resources:
- ../openeuler-website-docs/
- secrets.yaml
commonLabels:
  name: website-docs
commonAnnotations:
  email: 245462755@qq.com
  owner: zhengyuhang
patchesStrategicMerge:
- ingress.yaml
- deployment.yaml
namespace: website-docs
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-website-docs-ru
  newTag: v1.0.20230320082003
