# Deployment for meeting service
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: meeting-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meeting-server
      component: web-server
  template:
    metadata:
      labels:
        app: meeting-server
        component: web-server
    spec:
      containers:
        - name: meeting-server
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/app-meeting-server:f5af300fc61e33f1a3228a5981674622b0ca4285
          resources:
            requests:
              cpu: 2000m
              memory: 2000Mi
          env:
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: access_key_id
                  name: meeting-server-secrets
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: secret_access_key
                  name: meeting-server-secrets
            - name: WEBINAR_HOST
              valueFrom:
                secretKeyRef:
                  key: webinar_host
                  name: meeting-server-secrets
            - name: WEBINAR_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  key: webinar_template_id
                  name: meeting-server-secrets
            - name: OBS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: obs_endpoint
                  name: meeting-server-secrets
            - name: OBS_BUCKETNAME_SECOND
              valueFrom:
                secretKeyRef:
                  key: obs_bucketname_second
                  name: meeting-server-secrets
            - name: ZOOM_TOKEN
              valueFrom:
                secretKeyRef:
                  key: zoom_token
                  name: meeting-server-secrets
            - name: DB_USER
              value: root
            - name: TZ
              value: Asia/Shanghai
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db_password
                  name: meeting-server-secrets
            - name: DB_HOST
              value: 172.16.1.73
            - name: DB_PORT
              value: "3306"
            - name: WELINK_HOST_1
              valueFrom:
                secretKeyRef:
                  key: welink_host_1
                  name: meeting-server-secrets
            - name: WELINK_HOST_1_ACCOUNT
              valueFrom:
                secretKeyRef:
                  key: welink_host_1_account
                  name: meeting-server-secrets
            - name: WELINK_HOST_1_PWD
              valueFrom:
                secretKeyRef:
                  key: welink_host_1_pwd
                  name: meeting-server-secrets
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secret_key
                  name: meeting-server-secrets
            - name: APP_ID
              valueFrom:
                secretKeyRef:
                  key: app_id
                  name: meeting-server-secrets
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  key: app_secret
                  name: meeting-server-secrets
            - name: GMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  key: gmail_username
                  name: meeting-server-secrets
            - name: GMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: gmail_password
                  name: meeting-server-secrets
            - name: GENEGROUP_AUTH
              valueFrom:
                secretKeyRef:
                  key: genegroup_auth
                  name: meeting-server-secrets
            - name: SMTP_SERVER_HOST
              valueFrom:
                secretKeyRef:
                  key: smtp_server_host
                  name: meeting-server-secrets
            - name: QUERY_TOKEN
              valueFrom:
                secretKeyRef:
                  key: query_token
                  name: meeting-server-secrets
            - name: SMTP_SERVER_USER
              valueFrom:
                secretKeyRef:
                  key: smtp_server_user
                  name: meeting-server-secrets
            - name: SMTP_SERVER_PASS
              valueFrom:
                secretKeyRef:
                  key: smtp_server_pass
                  name: meeting-server-secrets
            - name: NEW_HOST_1
              valueFrom:
                secretKeyRef:
                  key: NEW_HOST_1
                  name: meeting-server-secrets
            - name: NEW_HOST_2
              valueFrom:
                secretKeyRef:
                  key: NEW_HOST_2
                  name: meeting-server-secrets
            - name: NEW_HOST_3
              valueFrom:
                secretKeyRef:
                  key: NEW_HOST_3
                  name: meeting-server-secrets
            - name: NEW_HOST_4
              valueFrom:
                secretKeyRef:
                  key: NEW_HOST_4
                  name: meeting-server-secrets
            - name: HOST_1_ACCOUNT
              valueFrom:
                secretKeyRef:
                  key: HOST_1_ACCOUNT
                  name: meeting-server-secrets
            - name: HOST_2_ACCOUNT
              valueFrom:
                secretKeyRef:
                  key: HOST_2_ACCOUNT
                  name: meeting-server-secrets
            - name: HOST_3_ACCOUNT
              valueFrom:
                secretKeyRef:
                  key: HOST_3_ACCOUNT
                  name: meeting-server-secrets
            - name: HOST_4_ACCOUNT
              valueFrom:
                secretKeyRef:
                  key: HOST_4_ACCOUNT
                  name: meeting-server-secrets
          command:
            - /bin/sh
            - -c
            - |
              # Fix wkhtmltopdf shared library issue when running on kernel which < 3.17
              # Read detail at https://stackoverflow.com/questions/54582864/missing-qt-libs-with-wkhtmltopdf-in-docker-on-debian-buster
              strip -R .note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.11.3
              # incase the __init__.py does not exist in the mounted volume
              touch /work/app-meeting-server/meetings/migrations/__init__.py
              python manage.py collectstatic
              # python manage.py makemigrations
              # python manage.py migrate
              exec uwsgi --ini /work/app-meeting-server/deploy/production/uwsgi.ini
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: schedule-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meeting-server
  template:
    metadata:
      labels:
        app: meeting-server
    spec:
      containers:
        - name: schedule-task
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/app-meeting-server:f5af300fc61e33f1a3228a5981674622b0ca4285
          env:
            - name: ZOOM_TOKEN
              valueFrom:
                secretKeyRef:
                  key: zoom_token
                  name: meeting-server-secrets
            - name: DB_USER
              value: root
            - name: TZ
              value: Asia/Shanghai
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db_password
                  name: meeting-server-secrets
            - name: DB_HOST
              value: 172.16.1.73
            - name: DB_PORT
              value: "3306"
            - name: HOST_GENEDNA
              valueFrom:
                secretKeyRef:
                  key: host_genedna
                  name: meeting-server-secrets
            - name: HOST_TOMMYLIKE
              valueFrom:
                secretKeyRef:
                  key: host_tommylike
                  name: meeting-server-secrets
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secret_key
                  name: meeting-server-secrets
            - name: APP_ID
              valueFrom:
                secretKeyRef:
                  key: app_id
                  name: meeting-server-secrets
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  key: app_secret
                  name: meeting-server-secrets
            - name: GMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  key: gmail_username
                  name: meeting-server-secrets
            - name: GMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: gmail_password
                  name: meeting-server-secrets
          command:
            - /bin/sh
            - -c
            - |
              python manage.py sendmessages

