apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/server-snippet: |
      rewrite ^/$ https://mailweb.osinfra.cn/postorius/lists/;
      location ^~ /admin {
        deny all;
      }
    nginx.ingress.kubernetes.io/custom-http-errors: "500"
  name: openlookeng-mailweb-ingress
spec:
  tls:
    - hosts:
        - mailweb.openlookeng.io
      secretName: openlookeng-mailweb-tls
  rules:
    - host: mailweb.openlookeng.io
      http:
        paths:
          - backend:
              serviceName: openlookeng-mailweb-internal
              servicePort: 80
            path: /
