---
kind: Service
apiVersion: v1
metadata:
  name: openlookeng-mailweb-internal
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 32717
---
kind: Endpoints
apiVersion: v1
metadata:
  name: openlookeng-mailweb-internal
subsets:
  - addresses:
      # These machines below are cluster workers in openlookeng cluster.
      - ip: 10.0.0.191
      - ip: 10.0.0.107
    ports:
      - port: 32727
