resources:
  - ingress.yaml
  - www-ingress.yaml
  - namespace.yaml
  - service.yaml
  - cibot-service.yaml
  - cache-ingress.yaml
  - oauth-proxy.yaml
  - secrets.yaml
commonLabels:
  app: openlookeng-website
patchesJson6902:
  - target:
      group: ""
      version: v1
      kind: Service
      name: openlookeng-website-internal
    path: selector.yaml
  - target:
      group: ""
      version: v1
      kind: Service
      name: openlookeng-bot-internal
    path: selector.yaml
namespace: openlookeng-website
