apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/permanent-redirect: https://openlookeng.io
  name: openlookeng-website-ingress
spec:
  tls:
    - hosts:
        - www.openlookeng.io
      secretName: openlookeng-website-tls
  rules:
    - host: www.openlookeng.io
      http:
        paths:
          - backend:
              serviceName: openlookeng-website-internal
              servicePort: 80
            path: /
