# Deployment for repo service
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: repo-server
spec:
  template:
    metadata:
      labels:
        app: repo-nginx-pod
    spec:
      nodeSelector:
        openeuler.ci/task: common
      containers:
        - name: repo-nginx
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/nginx-extras:1.20.0-with-fancy-templates-repo
          volumeMounts:
            - mountPath: /repo/openeuler
              name: data-volume
            - mountPath: /etc/rsyncd.secrets.ro
              name: rsync-secrets-volume
              subPath: rsyncd_secrets
          resources:
            requests:
              cpu: 300m
              memory: 2000Mi
          env:
            - name: TZ
              value: Asia/Shanghai
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /repo/openeuler
              exec nginx -g "daemon off;"
        - name: rsync-server
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/rsyncd:0.0.5
          volumeMounts:
            - mountPath: /etc/rsyncd.conf
              name: repo-nginx-configmap-volume
              subPath: rsyncd.conf
            - mountPath: /etc/rsyncd.secrets.ro
              name: rsync-secrets-volume
              subPath: rsyncd_secrets
            - mountPath: /repo/openeuler
              name: data-volume
            - mountPath: /root/.ssh/authorized_keys.ro
              name: repo-nginx-configmap-volume
              subPath: ssh.pub
          resources:
            requests:
              cpu: 300m
              memory: 2000Mi
      volumes:
        - name: rsync-secrets-volume
          secret:
            secretName: rsync-secrets
        - name: data-volume
          persistentVolumeClaim:
            claimName: openeuler-data-volume
