resources:
  - https://github.com/opensourceways/app-jenkins/deploy-without-agent?ref=stable
  - secrets.yaml
  - namespace.yaml
commonLabels:
  app: openeuler-jenkins
patchesStrategicMerge:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
patchesJson6902:
  - target:
      group: ""
      version: v1
      kind: Service
      name: jenkins
    path: selector.yaml
namespace: kunpeng

