apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: slavelistener
      port: 50000
      targetPort: 50000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent
spec:
  ports:
    - name: http
      port: 80
      # we need pin the node port here in order to be visitable via node
      targetPort: 8080
      nodePort: 30082
    - name: slavelistener
      port: 50000
      # we need pin the node port here in order to be visitable via node
      nodePort: 30052
      targetPort: 50000
  type: NodePort
