apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # TODO: mark this annotation is not working, we need figure how to handle this in the future.
    # cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: website-v2-ingress-backend
spec:
  tls:
    - hosts:
        - backup.openeuler.org
      secretName: website-tls
  rules:
    - host: backup.openeuler.org
      http:
        paths:
          - backend:
              serviceName: website-backend-service
              servicePort: 80
            path: /api(/|$)(.*)
