apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  name: mailweb-ingress
spec:
  tls:
    - hosts:
        - mailweb.openeuler.org
      secretName: mailweb-tls
  rules:
    - host: mailweb.openeuler.org
      http:
        paths:
          - backend:
              serviceName: mailman-web-service
              servicePort: 80
            path: /
