resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secrets.yaml
commonLabels:
  app: cve-manager
namespace: cve-manager
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/cve-manager
  newTag: 1f01bf8a60c6f599d954229549b179bf40d8a99d
