apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- discourse.yaml
- ingress.yaml
- secret.yaml
- namespace.yaml
- pvc.yaml
- redis.yaml
namespace: discourse
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/discourse
  newTag: v1.2.5
