resources:
- namespace.yaml
- ingress.yaml
- service.yaml
- deployment.yaml
- secret.yaml
namespace: openlookeng-docs
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openlookeng/openlookeng_website_docs
  newTag: 00950d23c193b1498e1e7949b37928320fa51818
