apiVersion: v1
kind: Service
metadata:
  name: openlookeng-website-docs-service
  namespace: openlookeng-docs
spec:
  ports:
    - name: http-port
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: openlookeng-website-docs
  type: ClusterIP
