# Deployment for repo service
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: repo-server
spec:
  strategy:
    # NOTE(tommylikehu): The strategy is recreate due to the multi-write issues if we running new pods while old one stays terminating.
    type: Recreate
  template:
    metadata:
      labels:
        app: repo-nginx-pod
    spec:
      containers:
        - name: repo-nginx
          volumeMounts:
            - mountPath: /repo/openeuler
              name: data-volume
            - mountPath: /etc/rsyncd.secrets.ro
              name: rsync-secrets-volume
              subPath: rsyncd_secrets
          resources:
            requests:
              cpu: 4000m
              memory: 6000Mi
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /repo/openeuler
              exec nginx -g "daemon off;"
        - name: fscrawler-client
          volumeMounts:
            - mountPath: /repo/openeuler
              name: data-volume
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: rsync-secrets
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: rsync-secrets
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p ~/.fscrawler/openeuler
              cp /fscrawler/_settings.yaml ~/.fscrawler/openeuler/_settings.yaml
              sed -i "s/<username>/${USERNAME}/g" ~/.fscrawler/openeuler/_settings.yaml
              sed -i "s/<password>/${PASSWORD}/g" ~/.fscrawler/openeuler/_settings.yaml
              exec fscrawler openeuler
        - name: rsync-server
          image: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/repo-client:cf6df893333da15daf1b0ade7ef03db3a83e1b6e
          volumeMounts:
            - mountPath: /etc/rsyncd.secrets.ro
              name: rsync-secrets-volume
              subPath: rsyncd_secrets
            - mountPath: /repo/openeuler
              name: data-volume
            - mountPath: /root/.ssh/authorized_keys.ro
              name: repo-nginx-configmap-volume
              subPath: ssh.pub
          env:
            - name: TARGET_DIR
              value: "/repo/openeuler"
            - name: RSYNC_INTERNAL
              value: "21600"
            - name: SYNC_HOST
              value: "rsync://root@121.36.97.194/openeuler"
            - name: ADDITIONAL_PARAMETERS
              value: "--delete"
          # Use the combination of sync & sleep to sync the repo from main repo periodically
          command:
            - /bin/sh
            - -c
            - |
              cp /etc/rsyncd.secrets.ro /etc/rsyncd.secrets
              chmod 0400 /etc/rsyncd.secrets
              exec tini -- entrypoint.sh
          resources:
            requests:
              cpu: 4000m
              memory: 8000Mi
      volumes:
        - name: rsync-secrets-volume
          secret:
            secretName: rsync-secrets
        - name: data-volume
          persistentVolumeClaim:
            claimName: openeuler-data-volume