---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: github-server
  namespace: openeuler-software-pkg
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: github-server
  template:
    metadata:
      labels:
        app: github-server
    spec:
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - name: github-server
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/software-package-github-server:1ff44243ce5364d6d5068e1db6c236d47508582b
        args:
        - --config-file=/opt/app/config/config.yaml
        - --github-token-path=/opt/app/config/oauth
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 500Mi
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: db_host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: db_user
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: db_pwd
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: db_name
        - name: KAFKA_ADDRESS
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: kafka_address
        - name: GITHUB_ROBOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: github_robot_username
        - name: GITHUB_ROBOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: github_token
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: encryption_key
        - name: ROBOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: software-pkg-secret
              key: robot_token
        volumeMounts:
        - mountPath: /opt/app/config/config.yaml
          name: server-configmap
          subPath: config.yaml
        - mountPath: /opt/app/config/oauth
          name: software-pkg-secret
          subPath: github_token
      volumes:
      - configMap:
          defaultMode: 420
          name: github-server-configmap
        name: server-configmap
      - name: software-pkg-secret
        secret:
          secretName: software-pkg-secret
        
      

