resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secrets.yaml
commonLabels:
  app: hdc-task-manager
namespace: hdc-task-manager
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/hdc-task-manager
  newTag: 9313ac8f130b49b9f1a7348c5de9d9dcfd32b7c4
