resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secrets.yaml
commonLabels:
  suit: openeuler-cve
namespace: cve
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/cve-backend
  newTag: 66991e17a34a1cd5692dedf70c9cb3186106809c
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/cve-manager
  newTag: 49e3f6a8852cc8132ec535acfcc28f359ce5ccf5
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/cve-manager-py
  newTag: 31dd2e1651a031c0cf5bb29869b2f1b721648bb6
