resources:
- https://github.com/opensourceways/compass-ci/deploy?ref=master
- ingress.yaml
commonLabels:
  app: compass-ci
namespace: compass-ci
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/compassciweb
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/compassciweb
  newTag: 18741183383c9513e99df71d67bb5e998f449f08.1600853199
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/compassciweb
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/compassciweb
  newTag: 06a93a5a1c6aa1b55ff861c27a4cbbc2b0927fce.1606577025
